## c++异常处理

Bug：思维不严谨有些情况没想到，导致程序中不可预期的执行

* 野指针



异常：可预期的分支执行

* a / b  (b = 0) 时异常停止
* 数组访问越界
* 打开文件 文件不存在



```c++
throw -> 抛出异常

// 类似 if{}  else{}
try{
	执行正确代码
} catch() {
	异常处理
}
```



eg:

```c++
#include <iostream>
#include <cstdio>

using namespace std;

double div(double a, double b) {
    const double x = 1e-9;
    double ret = 0.0;
    if (!((b > -x) && (b < x))) {
        ret = a / b;
    } else {
        throw 5;
    }
    return ret;
}

int main() {
    cout << div(1.0, 0.5) << endl;
    try {
        div(1.0, 0.0);
    } catch (int i) {
        cout << "b is zero !" << endl;
        cout << "catch(int i) : i = " << i << endl;
    }
    cout << "exception is dealed!" << endl;
    return 0;
}
```



**严格匹配**

```c++
try {
    throw 1;
} catch(char c) {
    cout << "catch(char c)" << c << endl;
} catch(short s) {
    cout << "catch(short s)" << s << endl;
} catch(double d) {
    cout << "catch(double d)" << d << endl;
} catch(int i) {
    cout << "catch(int i)" << i << endl;
} catch(...) {
    cout << "catch(...)" << endl;
}
cout << "finshed" << endl;
```

1. try后可以跟多个catch
2. catch ()中可以定义具体的异常类型
3. 不同类型异常由不同catch去处理
4. catch(...)是可以处理任意类型异常并且只能放在最后 
5. 任意一种类型异常只能被捕获一次



**匹配规则：**

* 自上而下严格匹配异常类型
* 匹配时不进行类型转换



**类类型的异常类匹配规则**

* 异常类可以是自定义类型的
* 同样自上而下严格匹配
* 父子兼容仍然适用
* * 匹配子类异常放在父类前



